// <auto-generated />
namespace SN_Aggregator_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TblMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TblMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202006161211004_TblMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
